name: Update Commit Logs

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/updates.md' # Avoid triggering the workflow when updates.md itself changes

jobs:
  update-logs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for pushing changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git log

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update commit logs
        run: pnpm update-logs

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes if needed
        run: |
          if [[ $(git status --porcelain docs/updates.md) ]]; then
            git add docs/updates.md
            git commit -m "chore: update commit logs [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
